name: baca_berita
description: newsreader application built using flutter with clean architecture implementation and dependency injection

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.3
  dartz: ^0.10.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
